//
// Created by Hodosi on 3/12/2021.
//

#ifndef ISOLATEDNODES_GRAPHISREGULAR_DISTANCEMATRIX_CONNECTED_CHECKISOLATEDNODES_H
#define ISOLATEDNODES_GRAPHISREGULAR_DISTANCEMATRIX_CONNECTED_CHECKISOLATEDNODES_H

#include <vector>

using namespace std;

void isolatedNodes(vector<int> &, vector<vector<int>>, int);
void printIsolatedNodes(vector<int>);

#endif //ISOLATEDNODES_GRAPHISREGULAR_DISTANCEMATRIX_CONNECTED_CHECKISOLATEDNODES_H
