//
// Created by Hodosi on 3/12/2021.
//

#ifndef ISOLATEDNODES_GRAPHISREGULAR_DISTANCEMATRIX_CONNECTED_WARSHALLALGORITM_H
#define ISOLATEDNODES_GRAPHISREGULAR_DISTANCEMATRIX_CONNECTED_WARSHALLALGORITM_H

#include <vector>

using namespace std;

void warshall(vector<vector<int>> &, vector<vector<int>>, int);

#endif //ISOLATEDNODES_GRAPHISREGULAR_DISTANCEMATRIX_CONNECTED_WARSHALLALGORITM_H
